import { env } from "../config/env.js";
import { logger } from "../config/logger.js";
import { query } from "../database/pool.js";
import { buildExecutiveReportForTenant } from "./executiveReportService.js";

const SCHEDULED_REPORT_ACTION = "planning.executive_report.scheduled.generated";

let timer = null;
let isRunning = false;

function clampInteger(value, fallback, min, max) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) {
    return fallback;
  }

  return Math.min(max, Math.max(min, Math.floor(parsed)));
}

function normalizeFrequency(value) {
  return String(value || "daily").toLowerCase() === "weekly" ? "weekly" : "daily";
}

function resolveWindowStart(now, frequency, hourUtc, minuteUtc) {
  const current = new Date(now);

  if (frequency === "weekly") {
    const currentUtcDay = current.getUTCDay();
    const daysFromMonday = (currentUtcDay + 6) % 7;
    const monday = new Date(Date.UTC(
      current.getUTCFullYear(),
      current.getUTCMonth(),
      current.getUTCDate() - daysFromMonday,
      hourUtc,
      minuteUtc,
      0,
      0
    ));

    if (current < monday) {
      monday.setUTCDate(monday.getUTCDate() - 7);
    }

    return monday;
  }

  const todayRun = new Date(Date.UTC(
    current.getUTCFullYear(),
    current.getUTCMonth(),
    current.getUTCDate(),
    hourUtc,
    minuteUtc,
    0,
    0
  ));

  if (current < todayRun) {
    todayRun.setUTCDate(todayRun.getUTCDate() - 1);
  }

  return todayRun;
}

async function hasRunInCurrentWindow(tenantId, windowStartIso) {
  const result = await query(
    `
      SELECT 1
      FROM audit_logs
      WHERE tenant_id = $1
        AND action = $2
        AND created_at >= $3
      LIMIT 1
    `,
    [tenantId, SCHEDULED_REPORT_ACTION, windowStartIso]
  );

  return result.rowCount > 0;
}

async function persistScheduledRun({ tenantId, windowStartIso, report, frequency }) {
  const payload = {
    template: "executive",
    scheduler: {
      frequency,
      windowStart: windowStartIso,
      generatedAt: report.generatedAt,
      template: "executive"
    },
    kpis: report.kpis,
    economics: report.report?.economics,
    recommendations: (report.recommendations || []).slice(0, 8)
  };

  await query(
    `
      INSERT INTO audit_logs (tenant_id, user_id, action, entity, entity_id, payload)
      VALUES ($1, NULL, $2, $3, $4, $5::jsonb)
    `,
    [
      tenantId,
      SCHEDULED_REPORT_ACTION,
      "planning_reports",
      `scheduler:${frequency}:${windowStartIso}`,
      JSON.stringify(payload)
    ]
  );
}

async function runSchedulerTick() {
  if (isRunning) {
    return;
  }

  isRunning = true;

  try {
    const now = new Date();
    const frequency = normalizeFrequency(env.executiveReportSchedulerFrequency);
    const hourUtc = clampInteger(env.executiveReportSchedulerHourUtc, 6, 0, 23);
    const minuteUtc = clampInteger(env.executiveReportSchedulerMinuteUtc, 0, 0, 59);
    const lookbackDays = clampInteger(env.executiveReportSchedulerLookbackDays, 14, 3, 120);

    const windowStart = resolveWindowStart(now, frequency, hourUtc, minuteUtc);
    const windowStartIso = windowStart.toISOString();

    const tenantsResult = await query(
      `
        SELECT id
        FROM tenants
        ORDER BY id ASC
      `
    );

    for (const tenant of tenantsResult.rows) {
      const tenantId = Number(tenant.id);
      if (!Number.isFinite(tenantId) || tenantId <= 0) {
        continue;
      }

      const alreadyRun = await hasRunInCurrentWindow(tenantId, windowStartIso);
      if (alreadyRun) {
        continue;
      }

      const to = new Date(now);
      const from = new Date(to.getTime() - lookbackDays * 24 * 3600 * 1000);

      const report = await buildExecutiveReportForTenant({
        tenantId,
        from,
        to,
        cadenceFrequency: frequency
      });

      await persistScheduledRun({
        tenantId,
        windowStartIso,
        report,
        frequency
      });

      logger.info(
        {
          tenantId,
          frequency,
          windowStart: windowStartIso,
          generatedAt: report.generatedAt
        },
        "Executive report generated by scheduler"
      );
    }
  } catch (error) {
    logger.error({ err: error }, "Executive report scheduler tick failed");
  } finally {
    isRunning = false;
  }
}

export function startExecutiveReportScheduler() {
  if (!env.executiveReportSchedulerEnabled) {
    logger.info("Executive report scheduler disabled by configuration");
    return;
  }

  const pollMs = clampInteger(env.executiveReportSchedulerPollMs, 300000, 60000, 86400000);

  if (timer) {
    clearInterval(timer);
  }

  runSchedulerTick().catch((error) => {
    logger.error({ err: error }, "Initial executive report scheduler run failed");
  });

  timer = setInterval(() => {
    runSchedulerTick().catch((error) => {
      logger.error({ err: error }, "Executive report scheduler run failed");
    });
  }, pollMs);

  logger.info(
    {
      frequency: normalizeFrequency(env.executiveReportSchedulerFrequency),
      hourUtc: env.executiveReportSchedulerHourUtc,
      minuteUtc: env.executiveReportSchedulerMinuteUtc,
      pollMs
    },
    "Executive report scheduler started"
  );
}

export function stopExecutiveReportScheduler() {
  if (timer) {
    clearInterval(timer);
    timer = null;
  }
}
